name: Bug Report (form)
description: Create a report to help us improve using a form
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: Describe_the_bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: To_Reproduce
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error 
    validations:
      required: true
  - type: textarea
    id: Expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: Version
    attributes:
      description: What version of the app are you using?
      label: App Info
      options:
        - Browser
        - Phone
        - Tablet
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
